# -*- coding: utf-8 -*-
"""Sales Data Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p44ON3x59lEdL65UjXqU6noj4e_NiRKA
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

df = pd.read_excel('/content/Walmart Sales.xlsx')

df.dropna(inplace=True)

df.head()

label_encoders = {}
categorical_cols = ['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Payment']
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

X = df[['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Payment']]
y_sales = df['Quantity']
y_revenue = df['Unit price'] * df['Quantity']  # Calculate revenue

X_train, X_test, y_sales_train, y_sales_test, y_revenue_train, y_revenue_test = train_test_split(X, y_sales, y_revenue, test_size=0.2, random_state=42)

rf_sales = RandomForestRegressor(n_estimators=100, random_state=42)
rf_sales.fit(X_train, y_sales_train)

rf_revenue = RandomForestRegressor(n_estimators=100, random_state=42)
rf_revenue.fit(X_train, y_revenue_train)

sales_predictions = rf_sales.predict(X_test)
revenue_predictions = rf_revenue.predict(X_test)

mae_sales = mean_absolute_error(y_sales_test, sales_predictions)
mse_sales = mean_squared_error(y_sales_test, sales_predictions)
r2_sales = r2_score(y_sales_test, sales_predictions)

mae_revenue = mean_absolute_error(y_revenue_test, revenue_predictions)
mse_revenue = mean_squared_error(y_revenue_test, revenue_predictions)
r2_revenue = r2_score(y_revenue_test, revenue_predictions)

print("Sales prediction evaluation:")
print("Mean Absolute Error:", mae_sales)
print("Mean Squared Error:", mse_sales)
print("R-squared:", r2_sales)

print("\nRevenue prediction evaluation:")
print("Mean Absolute Error:", mae_revenue)
print("Mean Squared Error:", mse_revenue)
print("R-squared:", r2_revenue)

import pandas as pd

# Load the dataset
df = pd.read_excel('/content/Walmart Sales.xlsx')

# Handle missing values if any
df.dropna(inplace=True)

# Group by 'Branch' and 'City' and calculate the average price
average_price_by_branch_city = df.groupby(['Branch', 'City'])['Unit price'].mean()

print("Average price of an item sold at each branch of the city:")
print(average_price_by_branch_city)

